[package]
name = "idle-hue"
version = "0.2.0"
edition = "2024"

[dependencies]
ui = { git = "https://github.com/cyypherus/ui" }
arboard = "3.4"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "process", "io-util", "time"] }
parley = "0.5.0"
reqwest = { version = "0.12", features = ["json", "stream"] }
tempfile = "3.8"
zip = "0.6"
semver = { version = "1.0", features = ["serde"] }
anyhow = { workspace = true }
log = "0.4"
dirs = "5.0"
env_logger = "0.11.8"
directories = "6.0.0"
color = "0.3.1"
kurbo = "0.11.3"

[package.metadata.bundle.bin.idle-hue]
name = "idle-hue"
identifier = "cyy.apps.idle-hue"
