[package]
name = "idle-hue"
version = "0.2.0"
edition = "2024"
default-run = "idle-hue"

[dependencies]
ui = { path = "../haven-ui" }
arboard = "3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.43.0", features = ["fs", "process", "io-util", "time"] }
vello_svg = "0.6.0"
parley = "0.5.0"
reqwest = { version = "0.12", features = ["json", "stream"] }
tempfile = "3.8"
zip = "0.6"
semver = { version = "1.0", features = ["serde"] }
anyhow = "1.0"
log = "0.4"
dirs = "5.0"
env_logger = "0.11.8"

[package.metadata.bundle.bin.idle-hue]
name = "idle-hue"
identifier = "cyy.apps.idle-hue"
