[package]
name = "bundler"
version = "0.2.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
clap = { version = "4.0", features = ["derive"] }

[features]
prod = []

[[bin]]
name = "bundler"
path = "src/main.rs"
